--- 
title: "An R companion"
author: "Eduardo Montoya"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
github-repo: emontoya2/csubRcomp-git
url: 'http\://www.csub.edu/~emontoya2/'
description: "A freely available document meant to help students learn R concurrently with the material of the course."
---



```{r setup, echo = FALSE, eval=TRUE,  message=FALSE,   warning=F}
knitr::opts_chunk$set(
  message = FALSE,
  fig.width = 5,
  fig.height = 4.5,
  comment = '#>',
  fig.align="center",
  collapse = TRUE,
  warning = FALSE,
  prompt=FALSE,
  echo = TRUE,
  eval= TRUE
  )
 
```

# Preface {-}


This document is freely available. There are grammatical errors in the document. If you do encounter a mistake or an error please inform me so that it can be corrected. If you would like to add material or have suggestions for material changes, then please contact me to include them in any future updates, and any contributions will be acknowledged. Keep in mind that this document is a work in progress, and the eventual goal is to make this document independent of any class textbook.

The first two chapters introduce one to the \textbf{R} environment and \textbf{RStudio} and some basic \textbf{R} functions so that one gets an idea of the ````''Look and Feel'' of \textbf{R} and \textbf{RStudio}. The last chapter discuss how to use \textbf{R} to carry out the analyses and techniques for some common areas covered in undergraduate regression analysis.

The best way to use this document is to apply a learn-by-doing approach. That is, don't just read through the \textbf{R} code given, but try the sample code given so that you understand what works and what does not. Finally, this document is not intended to be a know all guide but only a companion to your course. It is also worth noting that there are several ways to do the same thing in \textbf{R} and my hope is that I presented the easiest way(s).
 
 
